chapter_11/t3_rails/config/routes.rb
T3Rails::Application.routes.draw do
  devise_for :users

  resources :games do
    get 'join'
  end
  root to: "home#index"
end

chapter_11/t3_rails/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

chapter_11/t3_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

chapter_11/t3_rails/app/controllers/games_controller.rb
require 'socket'

class GamesController < ApplicationController
  before_filter :authenticate_user!

  # Listing all games 
  def index
    url = URI.parse("#{server_url}/games")
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) do |http|
      http.request(req)
    end 
    @games = JSON.parse(res.body)
  end

  # Player X joins a game
  def new
    url = URI.parse("#{server_url}/game?player_id=#{current_user.id}")
    req = Net::HTTP::Post.new(url.to_s)

    res = Net::HTTP.start(url.host, url.port) do |http|
      http.request(req)
    end 

    json = JSON.parse(res.body)

    if json["status"] == "success"
      game_id = json["data"]["game_id"]
      session[:side] = "x"
      redirect_to "/games/#{game_id}"
    else
      flash[:error] = "Error creating game: #{json["message"]}"
      redirect_to :back
    end
  end

  # Player O joins a game
  def join
    game_id = params[:game_id]
    url = URI.parse("#{server_url}/games/#{game_id}/join?player_id=#{current_user.id}")
    req = Net::HTTP::Post.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) do |http|
      http.request(req)
    end 
    json = JSON.parse(res.body)

    if json["status"] == "success"
      game_id = json["data"]["game_id"]
      session[:side] = "o"
      redirect_to "/games/#{game_id}"
    else
      flash[:error] = "Error joining game: #{json["message"]}"
      redirect_to :back
    end
  end 

private
  def server_url
    ip = Socket.ip_address_list.detect { |intf| intf.ipv4_private? }
    "http://#{ip.ip_address}:4000"
  end

end

chapter_11/t3_rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

chapter_11/t3_rails/app/helpers/application_helper.rb
module ApplicationHelper
  def random_md5
    Digest::MD5.hexdigest((0...8).map { (65 + rand(26)).chr }.join)
  end

  def identicon_link(md5)
    "http://www.gravatar.com/avatar/#{md5}?s=180&d=identicon"
  end

  def bootstrap_class_for flash_type
    case flash_type
    when :success
      "alert-success"
    when :error
      "alert-error"
    when :alert
      "alert-block"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end

end

chapter_11/t3_rails/app/views/games/_game.html.erb
<div class="col-md-4 column">
  <h5 class="text-center text-muted">
    <%= game["game_id"] %> 
  </h5>
  <%= image_tag identicon_link(game["game_id"]), width: '180px', class: 'center-block' %> 
  <br/>
  <div class="text-center">
    <p>
      <%= link_to 'Join', game_join_path(game["game_id"]), class: 'btn btn-success btn-lg' %>
    </p>
  </div>
</div>

chapter_11/t3_rails/app/views/games/index.html.erb
<h1 class="text-center">
  Listing Games
</h1>

<div class="row clearfix">
  <% @games.each do |game| %>
    <%= render 'game', game: game %>
  <% end %>
</div>

chapter_11/t3_rails/app/views/games/show.html.erb
<div class="row clearfix">
  <div class="col-md-12 column">
    <form role="form">
      <div class="form-group">
          <label for="server">Websocket Server</label>
          <span id="status" class="label label-success">Label</span>
          <input type="text" class="form-control" id="server" value="ws://localhost:4000/ws/<%= params[:id] %>"/>
      </div>
    </form>
  </div>
</div>

<div class="row clearfix">
  <div class="col-md-12 column">
    <div class="game-board">
      <input type="checkbox" id="1" class="game-board"/>
      <label for="1" class="game-board"></label>
      <input type="checkbox" id="2" class="game-board"/>
      <label for="2" class="game-board"></label>
      <input type="checkbox" id="3" class="game-board"/>
      <label for="3" class="game-board"></label>

      <input type="checkbox" id="4" class="game-board"/>
      <label for="4" class="game-board"></label>
      <input type="checkbox" id="5" class="game-board"/>
      <label for="5" class="game-board"></label>
      <input type="checkbox" id="6" class="game-board"/>
      <label for="6" class="game-board"></label>

      <input type="checkbox" id="7" class="game-board"/>
      <label for="7" class="game-board"></label>
      <input type="checkbox" id="8" class="game-board"/>
      <label for="8" class="game-board"></label>
      <input type="checkbox" id="9" class="game-board"/>
      <label for="9" class="game-board"></label>
    </div>
  </div>
</div>

<h2 class="text-center" id="outcome"></h2>

<div class="row clearfix">
  <div class="col-md-12 column">
    <div class="form-group">
      <label for="messages">Websocket Messages</label>
      <textarea class="form-control" rows="10" id="messages">
      </textarea>
    </div>
  </div>
</div>

<script>

var websocket;
$(document).ready(init);

function cross() {
		return '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px"' +              'width="100px" height="100px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">' +
						'<g id="Captions">' +
						'</g>' + 
						'<g id="Your_Icon">' + 
						'<path fill="#000000" d="M66.026,48.998l29.799-29.8c1.567-1.563,1.567-4.107,0-5.675L84.475,2.173' +      
									'c-1.567-1.567-4.107-1.567-5.676,0L49,31.972L19.201,2.173c-1.568-1.567-4.107-1.563-5.676,0L2.175,13.527' +   
									'c-1.567,1.567-1.567,4.107,0,5.675l29.8,29.8l-29.8,29.795c-1.567,1.568-1.567,4.111,0,5.68l11.351,11.351' +  
									'c1.568,1.567,4.107,1.563,5.676,0L49,66.027l29.799,29.8c1.568,1.567,4.108,1.567,5.676,0l11.351-11.354' +
									'c1.567-1.564,1.567-4.107,0-5.676L66.026,48.998z"/>'
						'</g>' +
						'</svg>';
}

function nought() {
		return '<svg version="1.1" id="svg2" inkscape:version="0.48.3.1 r9886" sodipodi:docname="circle1.svg"' + 
						'xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"' +
						'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:cc="http://creativecommons.org/ns#"' +
						'xmlns:svg="http://www.w3.org/2000/svg" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"' +
						'xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100px" height="100px"' +
						'viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve">' +
						'<path id="path2985" d="M50,0C22.386,0,0,22.386,0,50s22.386,50,50,50s50-22.386,50-50S77.614,0,50,0z M50,14.156' +
						'c19.799,0,35.844,16.044,35.844,35.844c0,19.799-16.045,35.844-35.844,35.844c-19.799,0-35.844-16.045-35.844-35.844' +
						'C14.156,30.201,30.201,14.156,50,14.156z"/>' +
						'</svg>';
}

function drawBoard(boardCells) {
  for (var i = 0; i < boardCells.length; i++) {
    var label = $("label[for='" + (i+1) + "']");

    if (boardCells[i] === "x") {
      label.html(cross());    
    } 
    else if (boardCells[i] === "o") {
      label.html(nought());
    } 
    else {
      label.html("");
    }
  }
}

function init() {
  if(!("WebSocket" in window)) {  
    $('#status').addClass("label-danger").text("Websockets UNSUPPORTED");
  } else {
    $('#status').addClass("label-error").text("Websockets SUPPORTED");
    connect();
  };
};

function connect() {
    wsHost = $("#server").val()
    websocket = new WebSocket(wsHost);
    showMessage('Connecting to: ' +  wsHost); 
    websocket.onopen = function(evt) { onOpen(evt) }; 
    websocket.onclose = function(evt) { onClose(evt) }; 
    websocket.onmessage = function(evt) { onMessage(evt) }; 
    websocket.onerror = function(evt) { onError(evt) }; 
};  

function disconnect() {
  websocket.close();
} 

function markBoard(gameId, side, playerId, pos) {
  if(websocket.readyState == websocket.OPEN){
      data = JSON.stringify({
        game_id: gameId,
        side: side, 
        player_id: playerId,
        pos: pos
      }); 

      websocket.send(data);

      showMessage('sending: ' + data); 
  } else {
      showMessage('websocket is not connected'); 
  };
};

function onOpen(evt) { 
  showMessage('********** CONNECTED **********'); 
  $("#connected").fadeIn('slow');
  $("#content").fadeIn('slow');
};  

function onClose(evt) { 
  showMessage(' ********** DISCONNECTED **********');
}  

function onMessage(evt) { 
  showMessage('RESPONSE: ' + evt.data); 
  try {
    json    = JSON.parse(evt.data);
    message = json["message"];
    data    = json["data"];
    board   = data["board"];
    outcome = data["outcome"];
    next    = data["next"];
    showOutcome(outcome, next);
    drawBoard(board);
  } catch(e) {
    console.log(e);
  }
}  

function onError(evt) {
  showMessage('ERROR: ' + evt.data);
}

function showMessage(txt) { 
  el = $('textarea#messages');
  el.val(txt + "\n" + el.val());
}

function showOutcome(outcome, next) {
  switch (outcome) {
    case "empty":
      $("#outcome").html("Waiting for Player O ...");
      break;
    case "in_progress":
      switch (next) {
        case "x":
          $("#outcome").html("Player X's turn.");
          break;
        case "o":
          $("#outcome").html("Player O's turn.");
          break;
      }
      if (next === "x") {
      } else if (next === "o") {

      }
      break;
    case "x_win":
      $("#outcome").html("Player X Wins!");
      break;
    case "o_win":
      $("#outcome").html("Player O Wins!");
      break;
    case "draw":
      $("#outcome").html("Draw!");
      break;
    case "game_full":
      $("#outcome").html("Game full!");
      break;
  }
}

$("input.game-board").click(function() {
  gameId   = "<%= params[:id] %>";
  playerId = "<%= current_user.id %>";
  side     = "<%= session[:side] %>";
  pos      = $(this).attr("id") + '';
  markBoard(gameId, side, playerId, pos); 
});
</script>

chapter_11/t3_rails/app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="text-center">
    T3 |> Tic Tac Toe in Elixir.
  </h1>
  
  <div class="col-md-12 column">
    <%= image_tag 'logo.png', width: '280px', class: 'center-block' %> 
  </div>
</div>
<div class="row clearfix">
  <div class="col-md-12 column text-center">
    <h1>
      Pick a side.
    </h1>
  </div>
</div>
<div class="row clearfix">
  <div class="col-md-6 column">
    <%= link_to (image_tag 'cross.png', width: '180px', class: 'center-block'), new_game_path %> 
    <h3 class="text-center text-muted">
      Create a Game.
    </h3>
  </div>
  <div class="col-md-6 column">
    <%= link_to (image_tag 'nought.png', width: '180px', class: 'center-block'), games_path %> 
    <h3 class="text-muted text-center">
      Join a Game.
    </h3>
  </div>
</div>

chapter_11/t3_rails/app/views/layouts/_header.html.erb
<div class="row clearfix">
  <div class="col-md-12 column">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> 
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button> 
        <a class="navbar-brand" href="#">
          <% if params[:id] %>
            <%= image_tag identicon_link(params[:id]), width: '50px' %> 
          <% else %>
            <%= link_to image_tag('logo.png', width: '50px'), root_path %>
          <% end %>
        </a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Create a Game', new_game_path %>
            </li>
            <li>
              <%= link_to 'Join a Game', games_path %>
            </li>
            <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>  
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</div>

chapter_11/t3_rails/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

chapter_11/t3_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tic Tac Toe in Elixir</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Elixir Tic Tac Toe">
  <meta name="author" content="Benjamin Tan Wei Hao">
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>